export const USER_PERMISSIONS = {
  MANAGE: 'USER:MANAGE',
  READ: 'USER:READ',
  UPDATE: 'USER:UPDATE',
  DELETE: 'USER:DELETE',
  CREATE: 'USER:CREATE',
};

export const REFERRAL_PERMISSIONS = {
  MANAGE: 'REFERRAL:MANAGE',
  READ: 'REFERRAL:READ',
  UPDATE: 'REFERRAL:UPDATE',
};

export const SYSTEM_CONFIG_PERMISSIONS = {
  CREATE: 'SYSTEM_CONFIG:CREATE',
  READ: 'SYSTEM_CONFIG:READ',
  UPDATE: 'SYSTEM_CONFIG:UPDATE',
  DELETE: 'SYSTEM_CONFIG:DELETE',
  MANAGE: 'SYSTEM_CONFIG:MANAGE',
};

export const CARD_PERMISSIONS = {
  CREATE: 'CARD:CREATE',
  READ: 'CARD:READ',
  UPDATE: 'CARD:UPDATE',
  DELETE: 'CARD:DELETE',
  MANAGE: 'CARD:MANAGE',
};

export const COUNTRY_PERMISSIONS = {
  READ: 'COUNTRY:READ',
  CREATE: 'COUNTRY:CREATE',
  UPDATE: 'COUNTRY:UPDATE',
  DELETE: 'COUNTRY:DELETE',
  MANAGE: 'COUNTRY:MANAGE',
};

export const TRANSACTION_PERMISSIONS = {
  READ: 'TRANSACTION:READ',
  CREATE: 'TRANSACTION:CREATE',
  UPDATE: 'TRANSACTION:UPDATE',
  DELETE: 'TRANSACTION:DELETE',
  MANAGE: 'TRANSACTION:MANAGE',
};

export const FAQ_PERMISSIONS = {
  CREATE: 'FAQ:CREATE',
  READ: 'FAQ:READ',
  UPDATE: 'FAQ:UPDATE',
  DELETE: 'FAQ:DELETE',
  MANAGE: 'FAQ:MANAGE',
};
