name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Run build step
        run: npm run build
